import { get_number, print } from './functions/io_utils.js'

const media = get_number('Media: ')
const num1 = get_number('1: ')
const num2 = get_number('2: ')
const num3 = get_number('3: ')
const num4 = get_number('4: ')
const num5 = get_number('5: ')
const num6 = get_number('6: ')
const num7 = get_number('7: ')
const num8 = get_number('8: ')
const num9 = get_number('9: ')
const num10 = get_number('10: ')
const num11 = get_number('11: ')
const num12 = get_number('12: ')
const num13 = get_number('13: ')
const num14 = get_number('14: ')
const num15 = get_number('15: ')
const num16 = get_number('16: ')

const y1 = get_number('1: ')
const y2 = get_number('2: ')
const y3 = get_number('3: ')
const y4 = get_number('4: ')
const y5 = get_number('5: ')
const y6 = get_number('6: ')
const y7 = get_number('7: ')
const y8 = get_number('8: ')
const y9 = get_number('9: ')
const y10 = get_number('10: ')
const y11 = get_number('11: ')
const y12 = get_number('12: ')
const y13 = get_number('13: ')
const y14 = get_number('14: ')
const y15 = get_number('15: ')
const y16 = get_number('16: ')

const respostaxy = ((num1 - media)*y1) + ((num2 - media)*y2) + ((num3 - media)*y3) + ((num4 - media)*y4) + ((num5 - media)*y5) + ((num6 - media)*y6) + ((num7 - media)*y7) + ((num8 - media)*y8) + ((num9 - media)*y9) + ((num10 - media)*y10) + ((num11 - media)*y11) + ((num12 - media)*y12) + ((num13 - media)*y13) + ((num14 - media)*y14) + ((num15 - media)*y15) + ((num16 - media)*y16)

print(`${respostaxy}`)